# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'actionTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'DevPlayIOS', :path => '~/.cocoapods/repos/DevPlayIOS/'
  # Pods for actionTest

  target 'actionTestTests' do
    inherit! :search_paths
    # Pods for testing
		
  end

  target 'actionTestUITests' do
    # Pods for testing
  end

end
