# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'actionTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'DevPlayIOS', :git => "https://chomg88@github.com/devsisters/devplay_ios.git"
  # Pods for actionTest

  target 'actionTestTests' do
    inherit! :search_paths
    # Pods for testing
		
  end

  target 'actionTestUITests' do
    # Pods for testing
  end

end
